# .github/workflows/ci.yml

name: CI - instruction-cli

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Using .x ensures the latest patch release for each version is used
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Check code formatting and quality (linter)
        run: npm run lint --if-present

      - name: Run startup check (smoke test)
        run: node inst.js --version
